version: "3.2"

# same as 
# docker run -p 8080:8080 -v $(pwd):/usr/src/app node_docker_setup_node

services:
  node:
    build: app
    volumes: 
      - ./:/usr/src/app
    #command: bash
    ports: 
      - "8080:8080"